using TokenOptimizer.Providers;
using TokenOptimizer.Sandbox;

namespace TokenOptimizer.Core.Tests.Sandbox;

public class ImageCatalogGoldenTests
{
    [Fact]
    public void GenerateDockerfile_MatchesGolden()
    {
        var catalog = new ImageCatalog(ToolCatalog.Tools);

        Assert.Equal(GoldenDockerfile, catalog.GenerateDockerfile());
    }

    [Fact]
    public void GenerateDockerfile_IsDeterministic()
    {
        var first = new ImageCatalog(ToolCatalog.Tools).GenerateDockerfile();
        var second = new ImageCatalog(ToolCatalog.Tools).GenerateDockerfile();

        Assert.Equal(first, second);
        Assert.False(first.Contains('\r'));
    }

    [Fact]
    public void GenerateDockerfile_BakesEveryToolFragmentVerbatimInCatalogOrder()
    {
        var output = new ImageCatalog(ToolCatalog.Tools).GenerateDockerfile();

        var offset = 0;
        foreach (var tool in ToolCatalog.Tools)
        {
            var at = output.IndexOf(tool.ImageInstallFragment, offset, StringComparison.Ordinal);
            Assert.True(at >= 0, $"fragment for '{tool.Id}' missing or out of order");
            offset = at + tool.ImageInstallFragment.Length;
        }

        Assert.Contains("NanoNets/Graft", output);
    }

    [Fact]
    public void Constructor_ReflectsInjectedToolsInsteadOfHardcodedCatalog()
    {
        var solo = new CompanionTool(
            Id: "only",
            HostInstallCommand: "host",
            ImageInstallFragment: "RUN echo only",
            ClaudeWiringFragment: "wire only");

        var output = new ImageCatalog([solo]).GenerateDockerfile();

        Assert.DoesNotContain("rtk", output);
        Assert.Contains("# [only]", output);
        Assert.Contains("RUN echo only", output);
        Assert.Contains("[only] wire only", output);
    }

    [Fact]
    public void Constructor_RejectsNullOrEmptyTools()
    {
        Assert.Throws<ArgumentNullException>(() => new ImageCatalog(null!));
        Assert.Throws<ArgumentException>(() => new ImageCatalog([]));
    }

    [Fact]
    public void DockerBuild_GeneratedDockerfileBuilds_WhenDockerPresent()
    {
        if (!IsEnabled) return;

        var dir = Path.Combine(Path.GetTempPath(), "tokenoptimizer-golden-smoke");
        Directory.CreateDirectory(dir);
        var dockerfile = Path.Combine(dir, "Dockerfile");
        File.WriteAllText(dockerfile, new ImageCatalog(ToolCatalog.Tools).GenerateDockerfile());

        var psi = new System.Diagnostics.ProcessStartInfo
        {
            FileName = "docker",
            Arguments = "build -t tokenoptimizer/agent-companion:golden-smoke .",
            WorkingDirectory = dir,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
        };
        using var proc = System.Diagnostics.Process.Start(psi)!;
        var stdout = proc.StandardOutput.ReadToEndAsync().Result;
        var stderr = proc.StandardError.ReadToEndAsync().Result;
        if (!proc.WaitForExit(1_200_000))
        {
            proc.Kill(true);
            Assert.Fail($"docker build timed out.{Environment.NewLine}{stderr}");
        }

        Assert.True(proc.ExitCode == 0, $"docker build failed:{Environment.NewLine}{stdout}{Environment.NewLine}{stderr}");
    }

    private static bool IsEnabled =>
        Environment.GetEnvironmentVariable("TOKENOPTIMIZER_DOCKER_TESTS") == "1"
        && DockerAvailable();

    private static bool DockerAvailable()
    {
        try
        {
            using var proc = System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
            {
                FileName = "docker",
                Arguments = "info",
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
            })!;
            proc.WaitForExit(15000);
            return proc.HasExited && proc.ExitCode == 0;
        }
        catch
        {
            return false;
        }
    }

    private const string GoldenDockerfile = """
# syntax=docker/dockerfile:1
# Generated by TokenOptimizer.Sandbox.ImageCatalog - DO NOT EDIT BY HAND.
# Single source of truth: TokenOptimizer.Providers.ToolCatalog (feeds host wiring AND image baking).
# Stage agent-base: node LTS + Claude Code CLI on top of opensandbox/code-interpreter.
# Stage agent-companion: companion tools + .claude wiring notes + graft workspace bootstrap entrypoint.

FROM opensandbox/code-interpreter AS agent-base

RUN apt-get update \
    && apt-get install -y --no-install-recommends bash ca-certificates curl git \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
    && apt-get install -y --no-install-recommends nodejs \
    && npm install -g @anthropic-ai/claude-code

FROM agent-base AS agent-companion

# --- companion tools (ToolCatalog order) ---

# [rtk]
RUN curl -fsSL https://raw.githubusercontent.com/rtk-ai/rtk/master/install.sh | bash

# [graphify]
RUN pip install --upgrade graphifyy

# [headroom]
RUN curl -fsSL https://raw.githubusercontent.com/henchmarketing-rgb/headroom/main/install.sh | bash

# [caveman]
RUN claude plugin marketplace add JuliusBrussee/caveman && claude plugin install caveman@caveman --scope user

# [claude-mem]
RUN npx -y claude-mem@latest install --ide claude-code

# [context7]
RUN claude mcp add --scope user context7 -- npx -y @upstash/context7-mcp

# [graft]
RUN npm install -g @nanonets/graft && graft init --agents claude --yes && graft build  # NanoNets/Graft: init wires .claude/, build generates the gitignored graft/ graph cache (--agents/--yes required without a TTY)

# --- .claude wiring notes (from ToolCatalog.ClaudeWiringFragment) ---
COPY <<'EOF' /opt/tokenoptimizer/WIRING.txt
[rtk] settings.json hooks.PreToolUse += {"type":"command","command":"%LOCALAPPDATA%\rtk\rtk.exe hook claude"} (merged by 'rtk init -g')
[graphify] ~/.claude/skills/graphify/SKILL.md + settings.json PreToolUse hook ('graphify claude install')
[headroom] ~/.claude/statusline.sh + settings.json statusLine command 'bash "<config-dir>/statusline.sh"' (python3 refs rewritten to an absolute interpreter)
[caveman] registered in ~/.claude/plugins/installed_plugins.json as caveman (scope=user, enabled=true); verified via 'claude plugin list'
[claude-mem] claude-mem's hooks in ~/.claude/settings.json (written by its installer); app sessions set CLAUDE_MEM_DATA_DIR=~/.claude-mem-tokenoptimizer and CLAUDE_MEM_WORKER_PORT=37778
[context7] user-scope MCP server context7 -> npx -y @upstash/context7-mcp ('claude mcp add --scope user')
[graft] .claude/skills/graft/SKILL.md + statusline and UserPromptSubmit/PostToolUse/SessionStart/Stop hooks merged into .claude/settings.json + MCP server in .mcp.json (all written by 'graft init')
EOF

# --- entrypoint: per-workspace graft bootstrap, then exec the container command ---
COPY <<'EOF' /usr/local/bin/tokenoptimizer-entrypoint
#!/bin/sh
set -e
if [ -d /workspace ]; then
    cd /workspace
    graft init --agents claude --yes
    graft build /workspace
fi
exec "$@"
EOF
RUN chmod +x /usr/local/bin/tokenoptimizer-entrypoint

WORKDIR /workspace
ENTRYPOINT ["/usr/local/bin/tokenoptimizer-entrypoint"]
CMD ["sleep", "infinity"]
""";
}
