namespace TokenOptimizer.Sandbox;

/// <summary>
/// Which sandbox image definition to generate. <see cref="AgentBase"/> is
/// the shared foundation image (node LTS + Claude Code CLI on top of the
/// pinned opensandbox base); <see cref="AgentCompanion"/> adds the companion
/// tools, wiring notes and graft-bootstrap entrypoint on the same lines.
/// </summary>
public enum AgentImageKind
{
    AgentBase,
    AgentCompanion,
}

/// <summary>
/// Generates the TokenOptimizer sandbox images as a single-document
/// Dockerfile per <see cref="AgentImageKind"/>, derived entirely from the
/// injected companion-tool list so that ToolCatalog stays the single source
/// of truth (the same catalog feeds host wiring and image baking).
///
/// Takes <see cref="CompanionTool"/> by constructor injection instead of a
/// project reference to TokenOptimizer.Providers: Providers references Core,
/// Core references Sandbox, so a Sandbox→Providers reference would close a
/// cycle. CompanionTool therefore lives here (bottom-most project) and the
/// golden tests construct ImageCatalog with ToolCatalog.Tools directly.
///
/// Output is deterministic: pure function of the constructor argument,
/// stable ToolCatalog order, '\n' line endings, no timestamps or ambient
/// state - asserted byte-for-byte by golden-file tests.
///
/// Ratified deviation: ClaudeWiringFragments contain Windows host paths, so
/// executing them inside a Linux build would fail; they are instead baked as
/// inert documentation into /opt/tokenoptimizer/WIRING.txt via a BuildKit
/// heredoc COPY.
/// </summary>
public sealed class ImageCatalog
{
    private const string BaseImage = "opensandbox/code-interpreter:v1.1.0";

    private readonly IReadOnlyList<CompanionTool> _tools;

    public ImageCatalog(IReadOnlyList<CompanionTool> tools)
    {
        ArgumentNullException.ThrowIfNull(tools);
        if (tools.Count == 0)
            throw new ArgumentException("At least one companion tool is required.", nameof(tools));
        _tools = tools;
    }

    /// <summary>
    /// Dockerfile text for <paramref name="kind"/>:
    /// <see cref="AgentImageKind.AgentBase"/> returns only the base stage
    /// (node LTS + Claude Code CLI on top of the pinned base image);
    /// <see cref="AgentImageKind.AgentCompanion"/> returns that same base
    /// content plus every tool's non-empty ImageInstallFragment verbatim in
    /// catalog order, the ClaudeWiringFragments as inert WIRING.txt notes,
    /// and an entrypoint block referencing the script produced by
    /// <see cref="GenerateEntrypointScript"/> at /usr/local/bin/tokenoptimizer-entrypoint.sh.
    /// </summary>
    public string GenerateDockerfile(AgentImageKind kind)
    {
        var lines = new List<string>
        {
            "# syntax=docker/dockerfile:1",
            "# Generated by TokenOptimizer.Sandbox.ImageCatalog - DO NOT EDIT BY HAND.",
            "# Single source of truth: TokenOptimizer.Providers.ToolCatalog (feeds host wiring AND image baking).",
            "",
            $"FROM {BaseImage}",
            "",
            "# node LTS + Claude Code CLI",
            "RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \\",
            "    apt-get install -y nodejs && \\",
            "    npm install -g @anthropic-ai/claude-code",
        };

        if (kind == AgentImageKind.AgentCompanion)
        {
            lines.Add("");
            lines.Add("# --- companion tools (ToolCatalog order) ---");
            foreach (var tool in _tools)
            {
                if (string.IsNullOrWhiteSpace(tool.ImageInstallFragment))
                    continue;
                lines.Add("");
                lines.Add($"# [{tool.Id}]");
                lines.Add(tool.ImageInstallFragment);
            }

            lines.Add("");
            lines.Add("# --- .claude wiring notes (from ToolCatalog.ClaudeWiringFragment; baked as inert documentation) ---");
            lines.Add("COPY <<'EOF_WIRING' /opt/tokenoptimizer/WIRING.txt");
            foreach (var tool in _tools)
            {
                if (string.IsNullOrWhiteSpace(tool.ClaudeWiringFragment))
                    continue;
                lines.Add($"[{tool.Id}] {tool.ClaudeWiringFragment}");
            }
            lines.Add("EOF_WIRING");

            lines.Add("");
            lines.Add("# --- entrypoint: per-workspace graft bootstrap, then exec the container command ---");
            lines.Add("COPY entrypoint.sh /usr/local/bin/tokenoptimizer-entrypoint.sh");
            lines.Add("RUN chmod +x /usr/local/bin/tokenoptimizer-entrypoint.sh");
            lines.Add("");
            lines.Add("WORKDIR /workspace");
            lines.Add("ENTRYPOINT [\"/usr/local/bin/tokenoptimizer-entrypoint.sh\"]");
            lines.Add("CMD [\"sleep\", \"infinity\"]");
        }

        return string.Join("\n", lines);
    }

    /// <summary>
    /// The container entrypoint baked into the companion image:
    /// bootstraps graft for the mounted workspace once per workspace
    /// (.graft-ready sentinel caches across restarts), tolerating first-boot
    /// failures via || true guards, then exec's the container command.
    /// </summary>
    public string GenerateEntrypointScript()
    {
        var lines = new[]
        {
            "#!/usr/bin/env bash",
            "set -e",
            "if [ -d /workspace ] && [ ! -f /workspace/.graft-ready ]; then",
            "  cd /workspace",
            "  graft init || true",
            "  graft build || true",
            "  touch /workspace/.graft-ready",
            "fi",
            "exec \"$@\"",
        };
        return string.Join("\n", lines);
    }
}
