namespace TokenOptimizer.Sandbox;

/// <summary>
/// Generates the TokenOptimizer sandbox images as a single multi-stage
/// Dockerfile, derived entirely from the injected companion-tool list so
/// that ToolCatalog stays the single source of truth (the same catalog
/// feeds host wiring and image baking).
///
/// Takes <see cref="CompanionTool"/> by constructor injection instead of a
/// project reference to TokenOptimizer.Providers: Providers references Core,
/// Core references Sandbox, so a Sandbox→Providers reference would close a
/// cycle. CompanionTool therefore lives here (bottom-most project) and the
/// golden tests construct ImageCatalog with ToolCatalog.Tools directly.
///
/// Output is deterministic: pure function of the constructor argument,
/// stable ToolCatalog order, '\n' line endings, no timestamps or ambient
/// state - asserted byte-for-byte by golden-file tests.
/// </summary>
public sealed class ImageCatalog
{
    private const string BaseImage = "opensandbox/code-interpreter";
    internal const string AgentBaseStage = "agent-base";
    internal const string AgentCompanionStage = "agent-companion";

    private readonly IReadOnlyList<CompanionTool> _tools;

    public ImageCatalog(IReadOnlyList<CompanionTool> tools)
    {
        ArgumentNullException.ThrowIfNull(tools);
        if (tools.Count == 0)
            throw new ArgumentException("At least one companion tool is required.", nameof(tools));
        _tools = tools;
    }

    /// <summary>
    /// Full multi-stage Dockerfile text:
    /// stage <c>agent-base</c> = node LTS + Claude Code CLI on top of
    /// <see cref="BaseImage"/>; stage <c>agent-companion</c> = every tool's
    /// ImageInstallFragment verbatim, its ClaudeWiringFragment baked into
    /// /opt/tokenoptimizer/WIRING.txt, and an entrypoint that bootstraps
    /// graft for the mounted workspace before exec'ing the container command.
    /// </summary>
    public string GenerateDockerfile()
    {
        var lines = new List<string>
        {
            "# syntax=docker/dockerfile:1",
            "# Generated by TokenOptimizer.Sandbox.ImageCatalog - DO NOT EDIT BY HAND.",
            "# Single source of truth: TokenOptimizer.Providers.ToolCatalog (feeds host wiring AND image baking).",
            $"# Stage {AgentBaseStage}: node LTS + Claude Code CLI on top of {BaseImage}.",
            $"# Stage {AgentCompanionStage}: companion tools + .claude wiring notes + graft workspace bootstrap entrypoint.",
            "",
            $"FROM {BaseImage} AS {AgentBaseStage}",
            "",
            "RUN apt-get update \\",
            "    && apt-get install -y --no-install-recommends bash ca-certificates curl git \\",
            "    && rm -rf /var/lib/apt/lists/*",
            "",
            "RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \\",
            "    && apt-get install -y --no-install-recommends nodejs \\",
            "    && npm install -g @anthropic-ai/claude-code",
            "",
            $"FROM {AgentBaseStage} AS {AgentCompanionStage}",
            "",
            "# --- companion tools (ToolCatalog order) ---",
        };

        foreach (var tool in _tools)
        {
            lines.Add("");
            lines.Add($"# [{tool.Id}]");
            lines.Add(tool.ImageInstallFragment);
        }

        lines.Add("");
        lines.Add("# --- .claude wiring notes (from ToolCatalog.ClaudeWiringFragment) ---");
        lines.Add("COPY <<'EOF' /opt/tokenoptimizer/WIRING.txt");
        foreach (var tool in _tools)
            lines.Add($"[{tool.Id}] {tool.ClaudeWiringFragment}");
        lines.Add("EOF");

        lines.Add("");
        lines.Add("# --- entrypoint: per-workspace graft bootstrap, then exec the container command ---");
        lines.Add("COPY <<'EOF' /usr/local/bin/tokenoptimizer-entrypoint");
        lines.Add("#!/bin/sh");
        lines.Add("set -e");
        lines.Add("if [ -d /workspace ]; then");
        lines.Add("    cd /workspace");
        lines.Add("    graft init --agents claude --yes");
        lines.Add("    graft build /workspace");
        lines.Add("fi");
        lines.Add("exec \"$@\"");
        lines.Add("EOF");
        lines.Add("RUN chmod +x /usr/local/bin/tokenoptimizer-entrypoint");

        lines.Add("");
        lines.Add("WORKDIR /workspace");
        lines.Add("ENTRYPOINT [\"/usr/local/bin/tokenoptimizer-entrypoint\"]");
        lines.Add("CMD [\"sleep\", \"infinity\"]");

        return string.Join("\n", lines);
    }
}
